id: A46889A88
base_file: fADD4.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:13:48.744425
  last_modified_at: 2022-06-11 13:13:48.744449
